# Generated by Django 2.0.13 on 2019-02-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('AP', 'Approved'), ('PR', 'Processing'), ('PD', 'Packed'), ('DP', 'Dispatched')], default='AP', max_length=2),
        ),
    ]
