# Generated by Django 2.0.13 on 2019-02-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190213_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Reason_delay',
            field=models.TextField(null=True),
        ),
    ]
