# Generated by Django 2.0.13 on 2019-02-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190214_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Reason_delay',
            field=models.TextField(blank=True, null=True),
        ),
    ]
