# Generated by Django 2.0.13 on 2019-02-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190214_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_details',
            field=models.TextField(null=True),
        ),
    ]
