# Generated by Django 2.0.13 on 2019-03-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
