# Generated by Django 2.0.13 on 2019-03-02 10:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='completion_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_order_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 2, 10, 11, 19, 781467, tzinfo=utc)),
        ),
    ]
