# Generated by Django 2.0.13 on 2019-03-02 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20190302_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
