# Generated by Django 2.0.13 on 2019-03-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20190302_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('AP', 'Approved'), ('PR', 'Processing'), ('PD', 'Packed'), ('DP', 'Dispatched')], default='AP', max_length=2),
        ),
    ]
