# Generated by Django 2.0.13 on 2019-03-03 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_product_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mill_name', models.CharField(max_length=200)),
                ('component_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1)),
                ('component_status', models.CharField(choices=[('NA', 'NoUpdate'), ('PR', 'Processing'), ('AQ', 'Acquired'), ('UT', 'Utilizing')], default='NA', max_length=2)),
                ('lead_time', models.IntegerField(default=2)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raws', to='myapp.Supplier')),
            ],
        ),
    ]
