# Generated by Django 2.0.13 on 2019-03-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recieved_date',
            field=models.DateTimeField(),
        ),
    ]
