# Generated by Django 2.0.13 on 2019-03-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20190303_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='completion_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='recieved_date',
            field=models.DateField(),
        ),
    ]
