# Generated by Django 2.0.13 on 2019-03-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20190303_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_delay',
            field=models.BooleanField(default=False),
        ),
    ]
